"dont run this file manually!"

ALTER TABLE `user` ADD `is_password_locked` INT(1) NULL DEFAULT NULL AFTER `last_edit_ip`;
ALTER TABLE `conversions` CHANGE `conversion_index` `conversion_index` DECIMAL(10,3) NULL DEFAULT NULL;


INSERT INTO `forms_search` (`id`, `theme`, `form_name`, `type`, `fields_order_primary`, `fields_order_secondary`) VALUES
(5, 'selio', 'Side page', 'MAIN', '{  \"PRIMARY\": {  \"SMART_SEARCH\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"full\", \"id\":\"NONE\", \"type\":\"SMART_SEARCH\"} ,\"TREE_79\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"79\", \"type\":\"TREE\"} ,\"TREE_64\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"64\", \"type\":\"TREE\"} ,\"INPUTBOX_36_TO\":{\"direction\":\"TO\", \"style\":\"\", \"class\":\"\", \"id\":\"36\", \"type\":\"INPUTBOX\"} ,\"INPUTBOX_20\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"20\", \"type\":\"INPUTBOX\"} }, \"SECONDARY\": {  \"CHECKBOX_22\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"22\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_24\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"24\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_28\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"28\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_32\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"32\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_23\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"23\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_31\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"31\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_30\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"30\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_33\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"33\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_25\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"25\", \"type\":\"CHECKBOX\"} } }', '0'),
(6, 'selio', 'top_custom_search', 'MAIN', '{  \"PRIMARY\": {  \"SMART_SEARCH\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"wide\", \"id\":\"NONE\", \"type\":\"SMART_SEARCH\"} ,\"TREE_79\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"79\", \"type\":\"TREE\"} ,\"TREE_64\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"64\", \"type\":\"TREE\"} ,\"INPUTBOX_36_FROM\":{\"direction\":\"FROM\", \"style\":\"\", \"class\":\"\", \"id\":\"36\", \"type\":\"INPUTBOX\"} ,\"INPUTBOX_36_TO\":{\"direction\":\"TO\", \"style\":\"\", \"class\":\"\", \"id\":\"36\", \"type\":\"INPUTBOX\"} ,\"INPUTBOX_20\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"20\", \"type\":\"INPUTBOX\"} ,\"DROPDOWN_MULTIPLE_2\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"2\", \"type\":\"DROPDOWN_MULTIPLE\"} ,\"DROPDOWN_38\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"38\", \"type\":\"DROPDOWN\"} }, \"SECONDARY\": {  \"CHECKBOX_22\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"22\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_24\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"24\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_28\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"28\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_31\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"31\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_30\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"30\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_33\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"33\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_27\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"27\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_32\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"32\", \"type\":\"CHECKBOX\"} } }', '0'),
(7, 'selio', 'top', 'MAIN', '{  \"PRIMARY\": {  \"SMART_SEARCH\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"NONE\", \"type\":\"SMART_SEARCH\"} ,\"TREE_79\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"79\", \"type\":\"TREE\"} ,\"C_PURPOSE\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"NONE\", \"type\":\"C_PURPOSE\"} ,\"INPUTBOX_36_TO\":{\"direction\":\"TO\", \"style\":\"\", \"class\":\"\", \"id\":\"36\", \"type\":\"INPUTBOX\"} }, \"SECONDARY\": {  \"CHECKBOX_25\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"25\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_28\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"28\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_22\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"22\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_24\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"24\", \"type\":\"CHECKBOX\"} ,\"CHECKBOX_11\":{\"direction\":\"NONE\", \"style\":\"\", \"class\":\"\", \"id\":\"11\", \"type\":\"CHECKBOX\"} } }', '0');

ALTER TABLE `property` ADD INDEX(`is_featured`);

ALTER TABLE `showroom_lang` CHANGE `body` `body` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;

ALTER TABLE `option`
ADD COLUMN `columns_number` INT(12) NULL DEFAULT NULL AFTER `is_not_translatable`

-- 1.6.7 END